{% set version = "1.5.0" %}

package:
  name: svg.py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/svg.py/svg_py-{{ version }}.tar.gz
  sha256: a036d0118176c2498601fab33b9b68dd9754e6a5fa12e4d36cce071b307b5c11

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - svg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/orsinium-labs/svg
  summary: SVG drawing library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
