schema_version: 1

context:
  version: "1.9.2"

package:
  name: svg.py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/svg.py/svg_py-${{ version }}.tar.gz
  sha256: 22b9881c580f55bf9d02e1a2c2d65ed05ed7d8a7d5467e847c5e1197ae0e3a9f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - svg
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: SVG drawing library
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/orsinium-labs/svg

extra:
  recipe-maintainers:
    - thewchan
